on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
#       with:
#         ref: master
      env:
        GIT_TRACE: 1
        GIT_CURL_VERBOSE: 1  
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: gautampachnanda-fork/dockerise-quay-io
        upstream_branch: main
        target_branch: main

    - name: Timestamp
      run: date
